replicaCount: 2

image:
  repository: <ECR_URI_REPOSITORY>  # e.g., 123456789012.dkr.ecr.ap-south-1.amazonaws.com/python-demo
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts:
    - host: example.your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: APP_ENV
    value: "dev"
  - name: GIT_COMMIT_SHA
    value: "local"

livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
